CREATE TABLE IF NOT EXISTS PRODUCT(
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NAME VARCHAR(50),
    PRICE DECIMAL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS PRODUCT_NAME_INDEX ON PRODUCT(NAME);

INSERT INTO PRODUCT (NAME,PRICE) VALUES ('Macbook', 10);